[assembly: System.Reflection.AssemblyTitle("Service Launcher")]
[assembly: System.Reflection.AssemblyDescription("Service Launcher")]
[assembly: System.Reflection.AssemblyCompany("Gareth Flowers")]
[assembly: System.Reflection.AssemblyProduct("Service Launcher")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Gareth Flowers 2015")]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Reflection.AssemblyCulture("")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.InteropServices.Guid("d889da6f-f048-4fce-9c3b-5c400fb58602")]
[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]